src_base: "/home/zhejiang/FireGuard_V2"

chipyard:
  dst_base: "/home/zhejiang/chipyard77"
  links:
    "Hardware/big.core/scala": "generators/boom/src/main/scala"
    "Hardware/LITTLE.core/scala": "generators/rocket-chip/src/main/scala"
    "Hardware/Top/scala": "generators/chipyard/src/main/scala"
    "Hardware/Firesim/scala": "generators/firechip/src/main/scala"
    "Software/bare-metal": "sims/verilator/bare-metal"

firesim:
  # Define multiple destination bases
  destinations:
    main: "/home/zhejiang/firesim/target-design/chipyard"
    firemarshal: "/home/zhejiang/firesim/sw/FireMarshal"
  
  links:
    "Hardware/big.core/scala": "main:generators/boom/src/main/scala"
    "Hardware/LITTLE.core/scala": "main:generators/rocket-chip/src/main/scala"
    "Hardware/Top/scala": "main:generators/chipyard/src/main/scala"
    "Hardware/Firesim/scala": "main:generators/firechip/src/main/scala"
    "Software/linux/parsecv3/firemarshal-workloads/parsecv3-workloads": "firemarshal:parsecv3-workloads" 